name: Project Manager
author: Jared Forsyth
version: 0.1
items:
- name: Design
  items:
  - flesh out the models
  - look at all the tasks that need to be done.
- name: Code
  items:
  - name: init
    items:
    - +super basic
    - work with .hg as well
  - name: project.yaml
    items:
    - parsing
    - writing
  - name: time tracker
    priority: 5
    description: >
      Somehow I think there should be a notion of "currently active project
      ... ish. or parent." such that instead of defaulting to working in the
      global context, it has you work on this project, whenever you just to
      "start", without any options. And if you do "new task", then its make as
      a child of this currently active thing. So I guess that would go in
      config, wouldnt it.

      Example use case: Coq. Thinking Im working on a particular file, so that
      would be a sub-project I imagine. And I want that to be the "cwd" as it
      were.
    items:
    - name: start
      description: >
        This would add an entry to the timesheet.yaml file, and have "active"
        be true, and not have an end time. Options:

        -n "task name" -p "parent fragment"

        If you give a parent fragment, it will search to see if that fragment
        is a unique initial sequence. If its not, it asks you to select from
        the matching list it found.
    - name: stop
      description: >
        This would turn off "active", and add the end time.
    - name: done
      description: >
        This would do the same as stop, but also add the "completed:true", and
        mark the current item "done"
    - name: resume
      description: >
        So this would start you working on the most recent thing you were
        working on that wasnt completed.
    - name: pause 
      description: >
        This would change  ,,, !!! So Im considering removing this. I dont
        know that it really adds value. I mean, maybe it does, but not atm.
- name: Website
  description: >
    Put together a nice-looking "intro to PM" site for us, to be hosted on
    gh-pages
- name: Vim integration
  description: >
    Man it would be super cool to have this totally vim integrated, so that
    when I'm doing coq proofs I can track my time super well. Man that would
    be really awesome.'
- name: Optimization
  description: >
    Is there any feasible way of making the startup time faster? Yaml is
    looking like a .3 second drag on the whole show. 
  items:
    - name: investigate yaml optimizations
      description: >
        investigate "roll my own pseudo-yaml" _or_ find another, faster
        library. Because startup time is important.
  
